# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoajax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoajaxitem',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
