# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortener',
            old_name='converted_url',
            new_name='code',
        ),
    ]
