# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('definition', models.CharField(max_length=200)),
                ('synonym', models.CharField(max_length=40)),
            ],
        ),
    ]
