# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainex', '0002_auto_20171106_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='email',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.PositiveIntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
