# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainex', '0003_auto_20171106_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
