# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainex', '0008_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='teach_boolean',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
